package bitwarden

import (
	"context"
	"net/http"
	"net/url"
	"strconv"
)

// Values the official command-line client identifies itself with. Servers
// check the device type on login and the client version on newer endpoints.
const (
	clientVersion    = "2026.6.0"
	deviceTypeLinux  = 25 // LinuxCLI
	deviceTypeHeader = "25"
)

// Device identifies this installation to the server. A stable identifier keeps
// the account's device list at one entry and avoids new-device notifications
// on every restart.
type Device struct {
	Identifier string
	Name       string
}

// TokenResponse is the identity server's answer to a login.
type TokenResponse struct {
	AccessToken string `json:"access_token"`
	ExpiresIn   int    `json:"expires_in"`
	TokenType   string `json:"token_type"`
	// The account's encrypted keys and KDF parameters travel with the token,
	// so unlocking needs no second request.
	Key                   string                 `json:"key"`
	PrivateKey            string                 `json:"privateKey"`
	Kdf                   int                    `json:"kdf"`
	KdfIterations         int                    `json:"kdfIterations"`
	KdfMemory             *int                   `json:"kdfMemory"`
	KdfParallelism        *int                   `json:"kdfParallelism"`
	UserDecryptionOptions *UserDecryptionOptions `json:"userDecryptionOptions"`
}

// UserDecryptionOptions carries the salt on servers that report it, which
// spares a client from decoding the email out of the access token.
type UserDecryptionOptions struct {
	MasterPasswordUnlock *struct {
		Salt string `json:"salt"`
	} `json:"masterPasswordUnlock"`
}

func (c *Client) identityToken(ctx context.Context, op string, form url.Values, dev Device) (*TokenResponse, error) {
	form.Set("deviceType", strconv.Itoa(deviceTypeLinux))
	form.Set("deviceIdentifier", dev.Identifier)
	form.Set("deviceName", dev.Name)
	var out TokenResponse
	err := c.do(ctx, request{
		op:     op,
		method: http.MethodPost,
		url:    c.identity + "/connect/token",
		form:   form,
		out:    &out,
	})
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LoginAPIKey logs in with a personal API key — the unattended login every
// deployment of this service uses.
func (c *Client) LoginAPIKey(ctx context.Context, clientID, clientSecret string, dev Device) (*TokenResponse, error) {
	return c.identityToken(ctx, "login_api_key", url.Values{
		"grant_type":    {"client_credentials"},
		"scope":         {"api"},
		"client_id":     {clientID},
		"client_secret": {clientSecret},
	}, dev)
}

// LoginPassword logs in with the master password hash. The service never uses
// it at runtime; it exists for provisioning and tests.
func (c *Client) LoginPassword(ctx context.Context, email, passwordHash string, dev Device) (*TokenResponse, error) {
	return c.identityToken(ctx, "login_password", url.Values{
		"grant_type": {"password"},
		"scope":      {"api offline_access"},
		"client_id":  {"cli"},
		"username":   {email},
		"password":   {passwordHash},
	}, dev)
}

// Registration is a new account, with every key generated by the client.
type Registration struct {
	Email              string              `json:"email"`
	Name               string              `json:"name"`
	MasterPasswordHash string              `json:"masterPasswordHash"`
	Key                string              `json:"key"`
	Kdf                int                 `json:"kdf"`
	KdfIterations      int                 `json:"kdfIterations"`
	Keys               RegistrationKeyPair `json:"keys"`
}

// RegistrationKeyPair is the account's RSA key pair.
type RegistrationKeyPair struct {
	PublicKey           string `json:"publicKey"`
	EncryptedPrivateKey string `json:"encryptedPrivateKey"`
}

// Register creates an account. Provisioning and tests only.
func (c *Client) Register(ctx context.Context, reg Registration) error {
	return c.do(ctx, request{
		op:     "register",
		method: http.MethodPost,
		url:    c.identity + "/accounts/register",
		body:   reg,
	})
}
